name: ci
on:
  pull_request:
    types: ["opened", "edited", "synchronize", "reopened"]
    branches: 
      - master
  push:
    branches:
    - master
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: install
      run: sudo apt-get update && sudo apt-get install -yq libfuse-dev pkg-config
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
