name: ci-test
on:
  pull_request:
    types: ["opened", "edited", "synchronize", "reopened"]
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        rust: ["1.39.0", "stable", "nightly"]
        
    steps:
      - name: install build deps
        if: startsWith(maxtrix.os, "ubuntu")
        run: sudo apt-get update && sudo apt-get install -yq libfuse-dev pkg-config
      - name: install build deps osx
        if: startsWith(maxtrix.os, "macos")
        run: brew update && brew install pkg-config && brew tap homebrew/cask && brew cask install osxfuse

